arr = [
    "analiza make-or-buy", 
    "use caseow", 
    "analize odchyleń wykorzystania zasobów", 
    "analize ryzyka w projekcie", 
    "backlog produktu", 
    "backlog sprintu",  
    "budżet projektu", 
    "burndownu", 
    "cykl życia projektu", 
    "daily scrum", 
    "epiki",
    "etapy projektu", 
    "fazy projektu", 
    "finansową ocena projektu", 
    "identyfikacji zagrożeń i szans w projekcie", 
    "interesariuszy projektu", 
    "karty projektu",
    "kluczowe czynniki jakościowe",
    "kluczowe wskaźniki efektywności",
    "lonceptualizacje",
    "manifest Agile",
    "PCM",
    "modele fazowe",
    "modele zespołów projektowych",
    "SOW",
    "optymalizacje czasu zadań"
    "optymalizacja wykorzystania zasobów",
    "produkt projektu",
    "produkty cząstkowe",
    "sprint review",
    "rejestr czynników ryzyka",
    "analize ryzyka rezydualnego",
    "studium wykonalności",
    "subprojekt",
    "szacowanie czasu trwania zadań",
    "środowisko realizacji projektu",
    "uzasadnienie projektu",
    "zakres projektu",
    "żelazny trójkąt"]