arr = [
    "beneficjentów",  
    "APM",  
    "bilansowania zasobów", 
    "CPM", 
    "decyzji środowiskowych", 
    "diagnozy w projekcie", 
    "DMAIC", 
    "dokumentowania wymagań klienta", 
    "dynamiki grupowa", 
    "eskalacji", 
    "estymacji czasu trwania zadań", 
    "ewaluacji projektu", 
    "extreme programming", 
    "facylitacji", 
    "Feature-Driven Development", 
    "free float", 
    "GERT", 
    "IPMA",
    "komisji oceny projektów",
    "komitetów sterujących",
    "kontroli w projekcie",
    "kryterii sukcesu i porażki zarządzania projektem",
    "mapy korzyści",
    "metody łańcucha krytycznego",
    "metody kontroli zasobów",
    "metodyki PRINCE II",
    "operacjonalizacji",
    "PERT",
    "planu projektu",
    "planowania ścieżki krytycznej",
    "prawa Parkinsona",
    "procedury budżetowania",
    "procesy projektowania",
    "reguły KISS",
    "retrospektywy",
    "test driven development",
    "zasade wąskiego gardła",
    "zasadę SMART"]
